/* eslint-disable sonarjs/no-duplicate-string */
import tShirt from 'assets/images/boy-white-black-t-shirt.jpg';
import baby from 'assets/images/baby.jpg';

const footerLinks = [
	{
		id: 1,
		title: 'Home & Living',
		links: [
			{
				id: 1,
				title: 'Curtains',
				to: '/',
			},
			{
				id: 2,
				title: 'Cushion Covers',
				to: '/',
			},
			{
				id: 3,
				title: 'Sofa Covers',
				to: '/',
			},
			{
				id: 4,
				title: 'Bedsheets',
				to: '/',
			},
			{
				id: 5,
				title: 'Bedding Sets',
				to: '/',
			},
			{
				id: 6,
				title: 'Pillows',
				to: '/',
			},
			{
				id: 7,
				title: 'Mattress Protectors',
				to: '/',
			},
			{
				id: 8,
				title: 'Duvet Covers',
				to: '/',
			},
			{
				id: 9,
				title: 'Blankets',
				to: '/',
			},
			{
				id: 10,
				title: 'Quilts',
				to: '/',
			},
			{
				id: 11,
				title: 'Doormats',
				to: '/',
			},
			{
				id: 12,
				title: 'Carpets',
				to: '/',
			},
			{
				id: 13,
				title: 'Bean Bags',
				to: '/',
			},
			{
				id: 14,
				title: 'Diwan Sets',
				to: '/',
			},
			{
				id: 15,
				title: 'Cushions',
				to: '/',
			},
			{
				id: 16,
				title: 'Face Towels',
				to: '/',
			},
			{
				id: 17,
				title: 'Towels',
				to: '/',
			},
			{
				id: 18,
				title: 'Trays',
				to: '/',
			},
			{
				id: 19,
				title: 'Coasters',
				to: '/',
			},
		],
	},
	{
		id: 2,
		title: 'Men Ethnicwear',
		links: [
			{
				id: 1,
				title: 'Men Kurtas',
				to: '/',
			},
			{
				id: 2,
				title: 'Men Ethnic Jackets',
				to: '/',
			},
			{
				id: 3,
				title: 'Men Velvet Sherwanis',
				to: '/',
			},
			{
				id: 4,
				title: 'Men Dhotis',
				to: '/',
			},
		],
	},
	{
		id: 3,
		title: 'Women Western Wear',
		links: [
			{
				id: 1,
				title: 'Women Frocks',
				to: '/',
			},
			{
				id: 2,
				title: 'Long Tops Women',
				to: '/',
			},
			{
				id: 3,
				title: 'Tshirt Dresses',
				to: '/',
			},
			{
				id: 4,
				title: 'Designer Gown',
				to: '/',
			},
			{
				id: 5,
				title: 'Pencil Skirts',
				to: '/',
			},
			{
				id: 6,
				title: 'Women Trousers',
				to: '/',
			},
			{
				id: 7,
				title: 'Flared Jeans',
				to: '/',
			},
			{
				id: 8,
				title: 'Women Sweatshirts',
				to: '/',
			},
			{
				id: 9,
				title: 'Shrugs',
				to: '/',
			},
			{
				id: 10,
				title: 'Capris',
				to: '/',
			},
			{
				id: 11,
				title: 'Jacket Dresses',
				to: '/',
			},
			{
				id: 12,
				title: 'Fancy Ladies Sweater',
				to: '/',
			},
			{
				id: 13,
				title: 'Chikankari Palazzos',
				to: '/',
			},
			{
				id: 14,
				title: 'Ankle Length Leggings',
				to: '/',
			},
			{
				id: 15,
				title: 'Tights',
				to: '/',
			},
			{
				id: 16,
				title: 'Printed Leggings',
				to: '/',
			},
			{
				id: 17,
				title: 'Kaftans',
				to: '/',
			},
			{
				id: 18,
				title: 'Maternity Wear',
				to: '/',
			},
			{
				id: 19,
				title: 'Denim Women Shorts',
				to: '/',
			},
			{
				id: 20,
				title: 'Black Jeggings',
				to: '/',
			},
			{
				id: 21,
				title: 'Short Night Dress',
				to: '/',
			},
			{
				id: 22,
				title: 'Women Night Suits',
				to: '/',
			},
			{
				id: 23,
				title: 'Lace Lingerie Sets',
				to: '/',
			},
			{
				id: 24,
				title: 'Lingerie Sets',
				to: '/',
			},
			{
				id: 25,
				title: 'Push Up Bra',
				to: '/',
			},
			{
				id: 26,
				title: 'Stockings',
				to: '/',
			},
			{
				id: 27,
				title: 'Black Camisoles',
				to: '/',
			},
			{
				id: 28,
				title: 'Cotton Bathrobes',
				to: '/',
			},
			{
				id: 29,
				title: 'Satin Night Suit',
				to: '/',
			},
			{
				id: 30,
				title: 'Body shapers',
				to: '/',
			},
			{
				id: 31,
				title: 'Women Pyjamas',
				to: '/',
			},
			{
				id: 32,
				title: 'Swimwear',
				to: '/',
			},
			{
				id: 33,
				title: 'Women Jackets',
				to: '/',
			},
			{
				id: 34,
				title: 'Women Thermal Set',
				to: '/',
			},
		],
	},
	{
		id: 4,
		title: 'Women Ethnicwear',
		links: [
			{
				id: 1,
				title: 'Silk Saree',
				to: '/',
			},
			{
				id: 2,
				title: 'Puff Sleeve Blouses',
				to: '/',
			},
			{
				id: 3,
				title: 'Chikankari Kurtis',
				to: '/',
			},
			{
				id: 4,
				title: 'Designer Lehenga',
				to: '/',
			},
			{
				id: 5,
				title: 'Sharara',
				to: '/',
			},
			{
				id: 6,
				title: 'Phulkari Dupatta',
				to: '/',
			},
			{
				id: 7,
				title: 'Petticoats',
				to: '/',
			},
			{
				id: 8,
				title: 'Abaya',
				to: '/',
			},
			{
				id: 9,
				title: 'Black Kurta',
				to: '/',
			},
			{
				id: 10,
				title: 'Velvet Shawls',
				to: '/',
			},
			{
				id: 11,
				title: 'Blouse Piece',
				to: '/',
			},
			{
				id: 12,
				title: 'Kurti Fabric',
				to: '/',
			},
			{
				id: 13,
				title: 'Designer Suits',
				to: '/',
			},
		],
	},
	{
		id: 5,
		title: 'Women Footwear',
		links: [
			{
				id: 1,
				title: 'Women Slippers',
				to: '/',
			},
			{
				id: 2,
				title: 'Bellies',
				to: '/',
			},
			{
				id: 3,
				title: 'Juttis & Mojaris',
				to: '/',
			},
		],
	},
	{
		id: 6,
		title: 'Women Accessories',
		links: [
			{
				id: 1,
				title: 'Hoop Earrings',
				to: '/',
			},
			{
				id: 2,
				title: 'Stud Earrings Women',
				to: '/',
			},
			{
				id: 3,
				title: 'Oxidised Ring',
				to: '/',
			},
			{
				id: 4,
				title: 'Handbags',
				to: '/',
			},
			{
				id: 5,
				title: 'Umbrellas',
				to: '/',
			},
			{
				id: 6,
				title: 'Cateye Sunglasses',
				to: '/',
			},
			{
				id: 7,
				title: 'Jewellery Set',
				to: '/',
			},
			{
				id: 8,
				title: 'Slingbags',
				to: '/',
			},
			{
				id: 9,
				title: 'Trolley Bags',
				to: '/',
			},
			{
				id: 100,
				title: 'Hijabs',
				to: '/',
			},
			{
				id: 10,
				title: 'Ankle Socks Women',
				to: '/',
			},
			{
				id: 11,
				title: 'Clutches',
				to: '/',
			},
			{
				id: 12,
				title: 'Hair Accessories',
				to: '/',
			},
			{
				id: 13,
				title: 'Maangtika',
				to: '/',
			},
			{
				id: 14,
				title: 'Pouches',
				to: '/',
			},
			{
				id: 15,
				title: 'Duffle Bags',
				to: '/',
			},
			{
				id: 16,
				title: 'Pashmina Shawls',
				to: '/',
			},
			{
				id: 17,
				title: 'Bindis',
				to: '/',
			},
			{
				id: 18,
				title: 'Waist Bags',
				to: '/',
			},
			{
				id: 19,
				title: 'Rucksacks',
				to: '/',
			},
			{
				id: 20,
				title: 'Briefcases',
				to: '/',
			},
			{
				id: 21,
				title: 'Small Travel Bags',
				to: '/',
			},
			{
				id: 22,
				title: 'Potlis',
				to: '/',
			},
			{
				id: 23,
				title: 'Nosepins',
				to: '/',
			},
			{
				id: 24,
				title: 'Gold Bangles',
				to: '/',
			},
			{
				id: 25,
				title: 'Bridal Anklets',
				to: '/',
			},
			{
				id: 26,
				title: 'Chandbali Earrings',
				to: '/',
			},
			{
				id: 27,
				title: 'Necklaces',
				to: '/',
			},
			{
				id: 28,
				title: 'Multi Necklace',
				to: '/',
			},
		],
	},
	{
		id: 7,
		title: 'Electronics & Accessories',
		links: [
			{
				id: 1,
				title: 'Android Smart Watches',
				to: '/',
			},
			{
				id: 2,
				title: 'On Ear Headphones',
				to: '/',
			},
			{
				id: 3,
				title: 'Bluetooth Speakers',
				to: '/',
			},
			{
				id: 4,
				title: 'Bluetooth Earphones',
				to: '/',
			},
			{
				id: 5,
				title: 'Sport Headphones',
				to: '/',
			},
			{
				id: 6,
				title: 'CCTV Cameras',
				to: '/',
			},
			{
				id: 7,
				title: 'Spy Cameras',
				to: '/',
			},
			{
				id: 8,
				title: 'Keyboard',
				to: '/',
			},
			{
				id: 9,
				title: 'Laptop Bags',
				to: '/',
			},
			{
				id: 10,
				title: 'Mouse',
				to: '/',
			},
			{
				id: 11,
				title: 'Laptop Accessories',
				to: '/',
			},
			{
				id: 12,
				title: 'Pen Drives',
				to: '/',
			},
			{
				id: 13,
				title: 'Earphones',
				to: '/',
			},
			{
				id: 14,
				title: 'Fast Charging Power Banks',
				to: '/',
			},
			{
				id: 15,
				title: 'Headphones',
				to: '/',
			},
			{
				id: 16,
				title: 'Data Cables',
				to: '/',
			},
			{
				id: 17,
				title: 'Car Mobile Holders',
				to: '/',
			},
			{
				id: 18,
				title: 'Car Mobile Holders',
				to: '/',
			},
			{
				id: 19,
				title: 'Mobile Chargers',
				to: '/',
			},
			{
				id: 20,
				title: 'Speakers',
				to: '/',
			},
			{
				id: 21,
				title: 'Diwali Lightings',
				to: '/',
			},
			{
				id: 22,
				title: 'Microphone',
				to: '/',
			},
			{
				id: 23,
				title: 'Memory Cards',
				to: '/',
			},
			{
				id: 24,
				title: 'Digital Photo Frames',
				to: '/',
			},
			{
				id: 25,
				title: 'Dongle',
				to: '/',
			},
			{
				id: 26,
				title: 'VR Box',
				to: '/',
			},
		],
	},
	{
		id: 8,
		title: 'Men Western Wear',
		links: [
			{
				id: 1,
				title: 'Cotton Shorts Men',
				to: '/',
			},
			{
				id: 2,
				title: 'Denim Jeans Men',
				to: '/',
			},
			{
				id: 3,
				title: 'Formal Trousers Men',
				to: '/',
			},
			{
				id: 4,
				title: 'Men Active Shorts',
				to: '/',
			},
			{
				id: 5,
				title: 'Sport Jackets Men',
				to: '/',
			},
			{
				id: 6,
				title: 'Printed Tshirts',
				to: '/',
			},
			{
				id: 7,
				title: 'Formal Shirts Men',
				to: '/',
			},
			{
				id: 8,
				title: 'Sleeveless Sweatshirts Men',
				to: '/',
			},
			{
				id: 9,
				title: 'Leather Jackets Men',
				to: '/',
			},
			{
				id: 10,
				title: 'Grey Blazers',
				to: '/',
			},
			{
				id: 11,
				title: 'Men Sweaters',
				to: '/',
			},
			{
				id: 12,
				title: 'Sport Tracksuits Men',
				to: '/',
			},
			{
				id: 13,
				title: 'Vests',
				to: '/',
			},
			{
				id: 14,
				title: 'Printed Briefs Men',
				to: '/',
			},
			{
				id: 15,
				title: 'Men Trunks',
				to: '/',
			},
			{
				id: 16,
				title: 'Wool Jackets Men',
				to: '/',
			},
		],
	},
	{
		id: 9,
		title: 'Men Footwear',
		links: [
			{
				id: 1,
				title: 'Reebok Sports Shoes Men',
				to: '/',
			},
			{
				id: 2,
				title: 'Men Sandals',
				to: '/',
			},
			{
				id: 3,
				title: 'Leather Loafers Men',
				to: '/',
			},
		],
	},
	{
		id: 10,
		title: 'Men Accessories',
		links: [
			{
				id: 1,
				title: 'Leather Watches Men',
				to: '/',
			},
			{
				id: 2,
				title: 'Gold Jewellery Men',
				to: '/',
			},
			{
				id: 3,
				title: 'Hair Spray For Men',
				to: '/',
			},
			{
				id: 4,
				title: 'Men Keychains',
				to: '/',
			},
			{
				id: 5,
				title: 'Men Socks',
				to: '/',
			},
			{
				id: 6,
				title: 'Men Scarves',
				to: '/',
			},
			{
				id: 7,
				title: 'Men Wrist Bands',
				to: '/',
			},
			{
				id: 8,
				title: 'Men Crossbody Bags',
				to: '/',
			},
			{
				id: 9,
				title: 'Men Shirt Studs',
				to: '/',
			},
		],
	},
	{
		id: 11,
		title: 'Kids',
		links: [
			{
				id: 1,
				title: 'Kids Lunch Boxes',
				to: '/',
			},
			{
				id: 2,
				title: 'Kids Ethnic Jackets',
				to: '/',
			},
			{
				id: 3,
				title: 'Kids Blazers',
				to: '/',
			},
			{
				id: 4,
				title: 'Rompers',
				to: '/',
			},
			{
				id: 5,
				title: 'Kids Kurtis & Kurtas',
				to: '/',
			},
			{
				id: 6,
				title: 'Kids Salwar Suit Sets',
				to: '/',
			},
			{
				id: 7,
				title: 'Kids Ethnic Gowns',
				to: '/',
			},
			{
				id: 8,
				title: 'Tshirts Boys',
				to: '/',
			},
			{
				id: 9,
				title: 'Girls Stylish Tops',
				to: '/',
			},
		],
	},
	{
		id: 12,
		title: 'Baby',
		links: [
			{
				id: 1,
				title: 'Baby Pillows',
				to: '/',
			},
			{
				id: 2,
				title: 'Baby Towels',
				to: '/',
			},
			{
				id: 3,
				title: 'Baby Hanging Cradle',
				to: '/',
			},
			{
				id: 4,
				title: 'Baby Sleeping Bag',
				to: '/',
			},
			{
				id: 5,
				title: 'Baby Blanket',
				to: '/',
			},
		],
	},
	{
		id: 13,
		title: 'Home & Kitchen',
		links: [
			{
				id: 1,
				title: 'Toaster',
				to: '/',
			},
			{
				id: 2,
				title: 'Mixer Grinder',
				to: '/',
			},
			{
				id: 3,
				title: 'Cookers',
				to: '/',
			},
			{
				id: 4,
				title: 'Juicer',
				to: '/',
			},
			{
				id: 5,
				title: 'Food Processors',
				to: '/',
			},
			{
				id: 6,
				title: 'Roti Maker',
				to: '/',
			},
			{
				id: 7,
				title: 'Sandwich Maker',
				to: '/',
			},
			{
				id: 8,
				title: 'Kettles',
				to: '/',
			},
			{
				id: 9,
				title: 'Hand Blender',
				to: '/',
			},
			{
				id: 10,
				title: 'Table Cover',
				to: '/',
			},
			{
				id: 11,
				title: 'Napkins Holder',
				to: '/',
			},
			{
				id: 12,
				title: 'Kitchen Mat',
				to: '/',
			},
			{
				id: 13,
				title: 'Kitchen Towel',
				to: '/',
			},
			{
				id: 14,
				title: 'Aprons',
				to: '/',
			},
			{
				id: 15,
				title: 'Kitchen Gloves',
				to: '/',
			},
			{
				id: 16,
				title: 'Racks & Holders',
				to: '/',
			},
			{
				id: 17,
				title: 'Spice Racks',
				to: '/',
			},
			{
				id: 18,
				title: 'Jars & Container',
				to: '/',
			},
			{
				id: 19,
				title: 'Water Bottles',
				to: '/',
			},
			{
				id: 20,
				title: 'Thermos & Flasks',
				to: '/',
			},
			{
				id: 21,
				title: 'Lunch Boxes',
				to: '/',
			},
			{
				id: 22,
				title: 'Salt & Pepper Shakers',
				to: '/',
			},
			{
				id: 23,
				title: 'Knives',
				to: '/',
			},
			{
				id: 24,
				title: 'Food Strainers',
				to: '/',
			},
			{
				id: 25,
				title: 'Choppers',
				to: '/',
			},
			{
				id: 26,
				title: 'Mashers',
				to: '/',
			},
			{
				id: 27,
				title: 'Graters',
				to: '/',
			},
			{
				id: 28,
				title: 'Cutlery',
				to: '/',
			},
			{
				id: 29,
				title: 'Chopping Boards',
				to: '/',
			},
			{
				id: 30,
				title: 'Kitchen Scissors',
				to: '/',
			},
			{
				id: 31,
				title: 'Ice Cube Trays',
				to: '/',
			},
			{
				id: 32,
				title: 'Juicer',
				to: '/',
			},
			{
				id: 33,
				title: 'Measuring Cups',
				to: '/',
			},
			{
				id: 34,
				title: 'Ice Cream Scoops',
				to: '/',
			},
			{
				id: 35,
				title: 'Funnels',
				to: '/',
			},
			{
				id: 36,
				title: 'Trivets',
				to: '/',
			},
		],
	},
	{
		id: 14,
		title: 'Personal Care & Wellness',
		links: [
			{
				id: 1,
				title: 'Trimmers',
				to: '/',
			},
			{
				id: 2,
				title: 'Makeup Kits',
				to: '/',
			},
			{
				id: 3,
				title: 'Hair Straighteners',
				to: '/',
			},
			{
				id: 4,
				title: 'Hair Dryers',
				to: '/',
			},
			{
				id: 5,
				title: 'Hair Care',
				to: '/',
			},
			{
				id: 6,
				title: 'Oral Care',
				to: '/',
			},
			{
				id: 7,
				title: 'Beard Oil',
				to: '/',
			},
			{
				id: 8,
				title: 'Deodorants',
				to: '/',
			},
			{
				id: 9,
				title: 'Kajal',
				to: '/',
			},
			{
				id: 10,
				title: 'Soap',
				to: '/',
			},
			{
				id: 11,
				title: 'Primer',
				to: '/',
			},
			{
				id: 12,
				title: 'Bb Cream',
				to: '/',
			},
			{
				id: 13,
				title: 'Body Scrub',
				to: '/',
			},
			{
				id: 14,
				title: 'Hair Oil',
				to: '/',
			},
			{
				id: 15,
				title: 'Talcum Powder',
				to: '/',
			},
			{
				id: 16,
				title: 'Foundation',
				to: '/',
			},
			{
				id: 17,
				title: 'Compact',
				to: '/',
			},
			{
				id: 18,
				title: 'Nail Polish',
				to: '/',
			},
			{
				id: 19,
				title: 'Lip Balm',
				to: '/',
			},
			{
				id: 20,
				title: 'Moisturizer',
				to: '/',
			},
			{
				id: 21,
				title: 'Eyeliner',
				to: '/',
			},
			{
				id: 22,
				title: 'Highlighter',
				to: '/',
			},
			{
				id: 23,
				title: 'Lipstick',
				to: '/',
			},
			{
				id: 24,
				title: 'Shopee',
				to: '/',
			},
		],
	},
];

const products = [
	{
		id: 1,
		image: tShirt,
		path: '/',
		title: 'Comfy Retro Men Tshirts',
		offerPrice: 234,
		originalPrice: 275,
		offer: 15,
		firstOrderOffer: 41,
		isFreeDelivery: true,
		totalReviews: 1234,
		rating: 3.6,
	},
	{
		id: 2,
		image: baby,
		path: '/',
		title: "Ethnic Fancy Silk Cotton Blend Kurta Kid's Boys Pyjama Set Vol 2",
		offerPrice: 192,
		originalPrice: 225,
		offer: 15,
		firstOrderOffer: 33,
		isFreeDelivery: false,
		totalReviews: 17089,
		rating: 4.1,
		offerDeliveryPrice: 63,
		actualDeliveryPrice: 70,
	},
	{
		id: 3,
		image: tShirt,
		path: '/',
		title: 'Comfy Retro Men Tshirts',
		offerPrice: 234,
		originalPrice: 275,
		offer: 15,
		firstOrderOffer: 41,
		isFreeDelivery: true,
		totalReviews: 1234,
		rating: 3.6,
	},
	{
		id: 4,
		image: baby,
		path: '/',
		title: "Ethnic Fancy Silk Cotton Blend Kurta Kid's Boys Pyjama Set Vol 2",
		offerPrice: 192,
		originalPrice: 225,
		offer: 15,
		firstOrderOffer: 33,
		isFreeDelivery: false,
		totalReviews: 17089,
		rating: 4.1,
		offerDeliveryPrice: 63,
		actualDeliveryPrice: 70,
	},
	{
		id: 5,
		image: tShirt,
		path: '/',
		title: 'Comfy Retro Men Tshirts',
		offerPrice: 234,
		originalPrice: 275,
		offer: 15,
		firstOrderOffer: 41,
		isFreeDelivery: true,
		totalReviews: 1234,
		rating: 3.6,
	},
	{
		id: 6,
		image: baby,
		path: '/',
		title: "Ethnic Fancy Silk Cotton Blend Kurta Kid's Boys Pyjama Set Vol 2",
		offerPrice: 192,
		originalPrice: 225,
		offer: 15,
		firstOrderOffer: 33,
		isFreeDelivery: false,
		totalReviews: 17089,
		rating: 4.1,
		offerDeliveryPrice: 63,
		actualDeliveryPrice: 70,
	},
	{
		id: 7,
		image: tShirt,
		path: '/',
		title: 'Comfy Retro Men Tshirts',
		offerPrice: 234,
		originalPrice: 275,
		offer: 15,
		firstOrderOffer: 41,
		isFreeDelivery: true,
		totalReviews: 1234,
		rating: 3.6,
	},
	{
		id: 8,
		image: baby,
		path: '/',
		title: "Ethnic Fancy Silk Cotton Blend Kurta Kid's Boys Pyjama Set Vol 2",
		offerPrice: 192,
		originalPrice: 225,
		offer: 15,
		firstOrderOffer: 33,
		isFreeDelivery: false,
		totalReviews: 17089,
		rating: 4.1,
		offerDeliveryPrice: 63,
		actualDeliveryPrice: 70,
	},
	{
		id: 9,
		image: tShirt,
		path: '/',
		title: 'Comfy Retro Men Tshirts',
		offerPrice: 234,
		originalPrice: 275,
		offer: 15,
		firstOrderOffer: 41,
		isFreeDelivery: true,
		totalReviews: 1234,
		rating: 3.6,
	},
	{
		id: 10,
		image: baby,
		path: '/',
		title: "Ethnic Fancy Silk Cotton Blend Kurta Kid's Boys Pyjama Set Vol 2",
		offerPrice: 192,
		originalPrice: 225,
		offer: 15,
		firstOrderOffer: 33,
		isFreeDelivery: false,
		totalReviews: 17089,
		rating: 4.1,
		offerDeliveryPrice: 63,
		actualDeliveryPrice: 70,
	},
	{
		id: 11,
		image: tShirt,
		path: '/',
		title: 'Comfy Retro Men Tshirts',
		offerPrice: 234,
		originalPrice: 275,
		offer: 15,
		firstOrderOffer: 41,
		isFreeDelivery: true,
		totalReviews: 1234,
		rating: 3.6,
	},
	{
		id: 12,
		image: baby,
		path: '/',
		title: "Ethnic Fancy Silk Cotton Blend Kurta Kid's Boys Pyjama Set Vol 2",
		offerPrice: 192,
		originalPrice: 225,
		offer: 15,
		firstOrderOffer: 33,
		isFreeDelivery: false,
		totalReviews: 17089,
		rating: 4.1,
		offerDeliveryPrice: 63,
		actualDeliveryPrice: 70,
	},
];

const productTypes = [
	{ id: 1, name: 'Category' },
	{ id: 2, name: 'Gender' },
	{ id: 3, name: 'Fabric' },
	{ id: 4, name: 'Color' },
	{ id: 5, name: 'Price' },
	{ id: 6, name: 'Discount' },
	{ id: 7, name: 'Rating' },
	{ id: 8, name: 'Size' },
	{ id: 9, name: 'Combo' },
	{ id: 10, name: 'Material' },
	{ id: 11, name: 'Bottom Length' },
	{ id: 12, name: 'Print Or Pattern Type' },
	{ id: 13, name: 'Bottom Style' },
	{ id: 14, name: 'Bottomwear Fabric' },
	{ id: 15, name: 'Ornamentation' },
	{ id: 16, name: 'Bottom Pattern Type' },
	{ id: 17, name: 'Border' },
	{ id: 18, name: 'Surface Styling' },
	{ id: 19, name: 'Back Type' },
	{ id: 20, name: 'Top Pattern' },
	{ id: 21, name: 'Fit/ Shape' },
	{ id: 22, name: 'Top Type' },
	{ id: 23, name: 'Brand' },
	{ id: 24, name: 'Compatible Models' },
	{ id: 25, name: 'Warranty Period' },
	{ id: 26, name: 'Bottom Type' },
	{ id: 27, name: 'Heel Type' },
	{ id: 28, name: 'Dial Design' },
	{ id: 29, name: 'Type' },
	{ id: 30, name: 'Type of Skin' },
	{ id: 31, name: 'Shade' },
	{ id: 32, name: 'Type of Hair' },
	{ id: 33, name: 'Language' },
	{ id: 34, name: 'Book Format' },
	{ id: 35, name: 'Board' },
	{ id: 36, name: 'Container Type' },
	{ id: 37, name: 'Brush Head Type' },
	{ id: 38, name: 'Refilling Type' },
	{ id: 39, name: 'Weight' },
	{ id: 40, name: 'Flavour' },
	{ id: 41, name: 'Region' },
];

const links = [
	{
		id: 1,
		text: 'Women Ethnic',
		to: '/',
		subMenus: [
			{
				id: 1,
				menuTitle: 'All Women Ethnic',
				menus: [{ id: 1, text: 'View All', to: '/' }],
			},
			{
				id: 2,
				menuTitle: 'Sarees',
				menus: [
					{ id: 1, text: 'All Sarees', to: '/' },
					{ id: 2, text: 'Silk Sarees', to: '/' },
					{ id: 3, text: 'Cotton Silk Sarees', to: '/' },
					{ id: 4, text: 'Cotton Sarees', to: '/' },
					{ id: 5, text: 'Georgette Sarees', to: '/' },
					{ id: 6, text: 'Chiffon Sarees', to: '/' },
					{ id: 7, text: 'Satin Sarees', to: '/' },
					{ id: 8, text: 'Embroidered Sarees', to: '/' },
				],
			},
			{
				id: 3,
				menuTitle: 'Kurtis',
				menus: [
					{ id: 1, text: 'All Kurtis', to: '/' },
					{ id: 2, text: 'Anarkali Kurtis', to: '/' },
					{ id: 3, text: 'Rayon Kurtis', to: '/' },
					{ id: 4, text: 'Cotton Kurtis', to: '/' },
					{ id: 5, text: 'Embroidered Kurtis', to: '/' },
				],
			},
			{
				id: 4,
				menuTitle: 'Suits & Dress Material',
				menus: [
					{ id: 1, text: 'All Suits & Dress Material', to: '/' },
					{ id: 2, text: 'Cotton Suits', to: '/' },
					{ id: 3, text: 'Embroidered Suits', to: '/' },
					{ id: 4, text: 'Chanderi Suits', to: '/' },
				],
			},
			{
				id: 5,
				menuTitle: 'Other Ethnic',
				menus: [
					{ id: 1, text: 'Blouses', to: '/' },
					{ id: 2, text: 'Dupattas', to: '/' },
					{ id: 3, text: 'Lehanga', to: '/' },
					{ id: 4, text: 'Gown', to: '/' },
					{ id: 5, text: 'Other Ethnic', to: '/' },
					{ id: 6, text: 'Ethnic Bottomwear', to: '/' },
				],
			},
			{
				id: 6,
				menuTitle: 'Kurta Sets',
				menus: [{ id: 1, text: 'All Kurta Sets', to: '/' }],
			},
		],
	},
	{ id: 2, text: 'Women Western', to: '/' },
	{ id: 3, text: 'Jewellery & Accessories', to: '/' },
	{ id: 4, text: 'Men', to: '/' },
	{ id: 5, text: 'Beauty & Health', to: '/' },
	{ id: 6, text: 'Bags & Footwear', to: '/' },
	{ id: 7, text: 'Home & Kitchen', to: '/' },
	{ id: 8, text: 'Kids', to: '/' },
	{ id: 9, text: 'Electronics', to: '/' },
];

export { footerLinks, productTypes, products, links };
